### ISSUE TITLE
Dispatching an async action (via Redux Thunk) causes an error by the time the inner subscribe callback runs

### ISSUE THREAD

**Issue by SudoPlz** [hindmost/reduxed-chrome-storage#1]
Hey there, the following line of code:

https://github.com/hindmost/reduxed-chrome-storage/blob/e4ff75608746c84f19590e689ae442ceb40b5eb0/src/ReduxedStorage.js#L119

generates this error:

```
index.esm.js?1aca:119 Uncaught (in promise) TypeError: Cannot read property 'getState' of null
    at eval (index.esm.js?1aca:119)
    at dispatch (redux.js?00d8:222)
    at eval (index.js?b083:11)
    at dispatch (redux.js?00d8:638)
    at Object.eval (recipe.actions.ts?5ca5:153)
    at step (recipe.actions.ts?5ca5:43)
    at Object.eval [as next] (recipe.actions.ts?5ca5:24)
    at fulfilled (recipe.actions.ts?5ca5:15)
```
looks like
https://github.com/hindmost/reduxed-chrome-storage/blob/e4ff75608746c84f19590e689ae442ceb40b5eb0/src/ReduxedStorage.js#L115
makes it null too soon.

I don't really understand the `buffStore` code tbh, and I also don't understand why 100ms isn't enough

(I assume you chose that value as a time that's more than enough for a reducer to complete it's work, correct? If not how did you pick that time?)

Please help.

p.s I'm using `redux-thunk` for async actions, not sure if that's relevant, since none of that affects the reducer, only what the actions return

**Comment by SudoPlz** [comment]
I think probably all that needs is to unsubscribe:

```
diff --git a/node_modules/reduxed-chrome-storage/lib/index.esm.js b/node_modules/reduxed-chrome-storage/lib/index.esm.js
index 268dc9f..9aaf715 100644
--- a/node_modules/reduxed-chrome-storage/lib/index.esm.js
+++ b/node_modules/reduxed-chrome-storage/lib/index.esm.js
@@ -115,7 +115,8 @@ class ReduxedStorage {
         this.buffStore = null;
       }, this.buffLife);
     }
-    this.buffStore.subscribe(() => {
+    let unsubscribe = this.buffStore.subscribe(() => {
+      unsubscribe();
       const state = this.buffStore.getState();
       if (isEqual(state, this.buffState0))
         return;

```

**Comment by SudoPlz** [comment]
Definitely relevant to using redux-thunk, because when using `redux-thunk` a call to https://github.com/hindmost/reduxed-chrome-storage/blob/e4ff75608746c84f19590e689ae442ceb40b5eb0/src/ReduxedStorage.js#L108 
(where action is basically just an async function and not a redux object)
could lead to more than 1 changes in redux. this library does not handle that properly atm :/

**Comment by hindmost** [comment]
Thanks for pointing out this issue. Sure it has to be fixed, but I'm a bit busy now, so it will take some time.
However I'd suggest you to consider (as an alternative approach) moving async logic outside action creators. See [this video lesson](https://egghead.io/lessons/javascript-redux-dispatching-actions-with-the-fetched-data) as well as [this article](https://levelup.gitconnected.com/how-to-build-a-rich-chrome-extension-quickly-with-create-react-app-and-redux-d9b64cf64832) for example.

**Comment by hindmost** [comment]
Hey again. Recently I've got some spare time and finally fixed this issue. Now it should work with async actions. I already tested out the fix (see updated tests). So I close this issue.
Please update this library to v1.1.0 in your project.
