### ISSUE TITLE
Async Actions

### ISSUE THREAD

**Issue by jmedina-loom** [hindmost/reduxed-chrome-storage#15]
Hello! 

[Loom](www.loom.com) is using this library to handle actions for our chrome extension. We found an issue when firing async thunk actions that causes the library to give unexpected side effects.

TLDR: When firing async thunk actions that dispatch multiple state changes, the component **ReduxStorage** only will trigger the first state change, save that change and then immediately unsubscribe.

Temporary Fix:
Debounce the unsubscribe listener

The video link describes the issue in detail:
https://www.loom.com/share/e8440a9d7f1f486981b293e640f6badc

**Comment by hindmost** [comment]
Hello.
The library should handle multiple async actions properly. I already made a test that shows it: https://github.com/hindmost/reduxed-chrome-storage/blob/master/test/async-actions.ts

It's unclear to me from your post what exactly your issue is. What do you mean by "async thunk actions that dispatch multiple state changes"? Do you really have an action (one action) that causes multiple state changes?

**Comment by jmedina-loom** [comment]
> What do you mean by "async thunk actions that dispatch multiple state changes"? Do you really have an action (one action) that causes multiple state changes?

It's very common to have actions like the following: 
```
export const batchAddTodos = (todos: string[]) => (dispatch: Dispatch) => {
  todos.forEach((todo) => {
    dispatch(addTodo(todo));
  });
};
```
Here is a simple test case. 
```javascript
  describe("multiple state actions", () => {
    it("creates a store and dispatches an action with multiple state changes", async () => {
      const store: any = await storeCreatorFactory()(
        todosReducer,
        applyMiddleware(thunk)
      );

      const clock = sinon.useFakeTimers();

      expect(store.getState()).to.eql([]);
      store.dispatch(batchAddTodos(["todo1", "todo2", "todo3", "todo4"]));
      clock.tick(1);
      expect(store.getState()).to.eql([
        { id: 1, text: "todo1", completed: false },
        { id: 2, text: "todo2", completed: false },
        { id: 3, text: "todo3", completed: false },
        { id: 4, text: "todo4", completed: false },
      ]);
      clock.restore();
    });
  });
```

Here are the results: 
```
  1) Async actions
       multiple state actions
         creates a store and dispatches an action with multiple state changes:

      AssertionError: expected [ { id: 1, text: 'todo1', …(1) } ] to deeply equal [ Array(4) ]
      + expected - actual

           "completed": false
           "id": 1
           "text": "todo1"
         }
      +  {
      +    "completed": false
      +    "id": 2
      +    "text": "todo2"
      +  }
      +  {
      +    "completed": false
      +    "id": 3
      +    "text": "todo3"
      +  }
      +  {
      +    "completed": false
      +    "id": 4
      +    "text": "todo4"
      +  }
       ]
```

**Comment by hindmost** [comment]
Thanks for reporting this issue. And special thanks for the test case. Now it's obvious

**Comment by hindmost** [comment]
I applied your fix in minor release v2.7.0. Please check out the update in your project.

**Comment by hindmost** [comment]
FYI, now I'm working on next major version (v3). It will get a lot of changes incl. getting rid of timers (setTimeout) and Redux Toolkit support. I'm going to release it in a few weeks.

**Comment by jmedina-loom** [comment]
Fantastic. Thanks for the quick fix. I look forward to the next version!

**Comment by hindmost** [comment]
Hello again.
[v3](https://github.com/hindmost/reduxed-chrome-storage/releases/tag/3.0.0) is released now! Please check out the new version in your project.

P.S.: Don't forget (I mean the Loom team, not you personally) to include the copyright notice somewhere in your extension files as the MIT license requires. If you use a bundler like Webpack it should most likely do it autom'ly.

**Comment by jmedina-loom** [comment]
Congrats on the v3 release 🎉 . The MIT license is included in our bundle (we are using Webpack). We will be using this library for our upcoming release next year. Thanks again 😄
