### ISSUE TITLE
Iframe Handling

### ISSUE THREAD

**Issue by adelin-b** [hindmost/reduxed-chrome-storage#19]
Hello, 
In the documentation it says to only infor createReduxed storage once per components, but for content.js I have to call it twice, once with content, once inside an iframe.
I got trouble because the redux changes that happen inside the iframe seems not communicated to the content, background scripts etc.

Maybe you already thought this throught and im not doing it right. Would love to hear about how to do it.

**Comment by hindmost** [comment]
Most likely you forgot to specify [`all_frames`](https://developer.chrome.com/docs/extensions/mv3/content_scripts/#frames) flag.
