### ISSUE TITLE
How would you feel about a Typescript version of this lib?

### ISSUE THREAD

**Issue by magne4000** [hindmost/reduxed-chrome-storage#2]
Your lib seems great! But I miss the typings 😢 
The lib is quite simple, so it could be rewritten in Typescript.
One could write a @types package, but it duplicates the work, and its often out-of-sync.

So how would you feel if I created a Pull Request to transform this repo to typescript?

**Comment by hindmost** [comment]
Thanks for feedback!
I wouldn't mind TS support. However I wouldn't like to include TS as a dependency.
I think [including declaration file](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package) into the lib is enough to use it in TS projects, am I right?
If so, could you please write such declaration file for this repo?

**Comment by magne4000** [comment]
Would be possible yes

**Comment by magne4000** [comment]
Just to let you know, I've switch from redux to [hookstate](https://hookstate.js.org/), and also made the [same kind of extension](https://github.com/getstation/hookstate-plugin-web-extension#forward-partial-updates-of-the-tree-through-browser-storage) to share the state thanks to `browser.storage`, but based on a different principle. I'd be happy to have your feedback.
So that also mean that I'll probably not be doing the TS version of `reduxed-chrome-storage` anytime soon, sorry 😅

**Comment by hindmost** [comment]
No problem, I'll do it myself. Anyway I'm grateful to you for your feedback.

Regarding your plugin for hookstate. I'm not familiar with hookstate, but AFAIU it's all about React and its Hooks feature. Although I love React too, I don't think it's a good idea to use it everywhere. There are cases where React's just inappropriate. For example, background scripts within browser extensions aren't supposed to render anything in DOM. Using your plugin along with hookstate in a background script would mean including React (as a peer dependency of hookstate) into the respective built file, which seems a useless expense. In contrast, Redux doesn't require React (as well as any other dependency) and therefore looks preferable to hookstate, at least to me.

**Comment by hindmost** [comment]
Hey there. I fully rewritten this library in TypeScript, so now it may be used in TypeScript projects. See my new release - [v2.0.0](https://github.com/hindmost/reduxed-chrome-storage/releases/tag/2.0.0).
If you use this library in your projects please update it to v2.0.0 there.
