### ISSUE TITLE
Having trouble with set up 

### ISSUE THREAD

**Issue by williamlmao** [hindmost/reduxed-chrome-storage#4]
Hi! Thanks for building this library. The set up instructions are unclear to me. 

Here's what I'm trying currently: 

```
import React from 'react';
import { render } from 'react-dom';
import { createStore } from 'redux';
import { Provider } from 'react-redux';
import reducers from '../Reducers';
import storeCreatorFactory from 'reduxed-chrome-storage';
import Popup from './Popup';
import './index.css';


const options = {
  createStore: createStore,
};
const asyncStoreCreator = storeCreatorFactory(options);
const store = asyncStoreCreator(reducers).then((store) => {
  const state = store.getState();
  console.log('asyncStoreCreator state', state);
});

render(
  <Provider store={store}>
    <Popup />
  </Provider>,
  window.document.querySelector('#app-container')
);
```
I'm not getting an error that looks like it's calling out anything with the library or my reducers file, but when I load the extension it comes out blank. If I remove the code relating to this library, my extension loads just fine. What am I getting wrong here?

**Comment by hindmost** [comment]
It seems that you haven't read the Readme attentively. With Promise-based usage all code that depends on Redux store has to be placed _**inside**_ Promise callback, not outside as in your sample.

BTW, you could star this repo if it's really useful for you.
