### ISSUE TITLE
How to add redux-thunk ?

### ISSUE THREAD

**Issue by honeybread** [hindmost/reduxed-chrome-storage#5]
I'm looking at the documentation but I'm not sure how to add redux-thunk middleware to createStore. My code currently looks like this:

 
```
import { createStore, applyMiddleware } from "redux";
import thunk from "redux-thunk";
import storeCreatorFactory from "reduxed-chrome-storage";
import rootReducer from "./redux/reducers/index";

const options = {
  createStore: createStore,
  storageArea: "local",
};
const asyncStoreCreator = storeCreatorFactory(options);

const getStore = asyncStoreCreator(rootReducer);

export { getStore };
```

Normally I would add middleware as an argument to createStore like so:

```
const store = createStore(
        rootReducer,
        applyMiddleware(thunk))
```

But since createStore option in reduxed-chrome-storage accepts only function, I'm not sure how to add middleware while using reduxed-chrome-storage. 

Could someone help me with this? Thank you!

**Comment by honeybread** [comment]
Sorry for the trouble. I figured it out myself.

asyncStoreCreator takes a second argument. So you can pass middleware like so:

```
import { createStore, applyMiddleware } from "redux";
import thunk from "redux-thunk";
import storeCreatorFactory from "reduxed-chrome-storage";
import rootReducer from "./redux/reducers/index";

const options = {
  createStore: createStore,
  storageArea: "local",
};
const asyncStoreCreator = storeCreatorFactory(options);

const getStore = asyncStoreCreator(rootReducer, applyMiddleware(thunk));

export { getStore };
```

**Comment by hindmost** [comment]
@honeybread You could give this library a star if it's useful for you
