### ISSUE TITLE
Access redux store in service worker

### ISSUE THREAD

**Issue by smartify-jia** [hindmost/reduxed-chrome-storage#7]
Hi there,
Thanks for building this awesome library.
The Redux store is currently sitting on the content script. 
Just wondering if I am able to access the store from the service worker too? 

Thanks in advance

**Comment by hindmost** [comment]
It seems you haven't paid attention to README.
With this library you **should not** call/use Redux directly. You have to replace each call of `createStore()` in your code with `asyncStoreCreator` that is returned by `storeCreatorFactory`. See README for details.
