### ISSUE TITLE
Cannot convert undefined or null to object in mergeOrReplace when state contains property with a null value

### ISSUE THREAD

**Issue by nopol10** [hindmost/reduxed-chrome-storage#8]
As mentioned in the title, I get the error when running `asyncStoreCreator` when my state contains a null value. Making the change to `mergeOrReplace` appears to resolve it, however I just want to make sure that this logic is correct so I've pasted the code here:

```javascript
function mergeOrReplace(a, b) {
    if (Array.isArray(b))
        return cloneDeep(b);
    if (typeof a !== 'object' || Array.isArray(a) || typeof b !== 'object' || a === null || b === null)
        return (typeof b !== 'undefined' && b !== null) ? b : a;
    return Object.keys(a).concat(Object.keys(b).filter(key => !a[key])).reduce((acc, key) => {
        return acc[key] = mergeOrReplace(a[key], b[key]), acc;
    }, {});
}
```

**Comment by hindmost** [comment]
Thanks for pointing that out. I'll make the needed fixes soon.

**Comment by hindmost** [comment]
Done. Now it shouldn't throw that error. I already [tested it out](https://github.com/hindmost/reduxed-chrome-storage/blob/master/test/mergeOrReplace.ts). So I close this issue.
Please update this library to the latest version in your project: v2.4.8.
